"""TechAccess Remediator — AI-powered code fix generation.

Generates HTML/ARIA code fixes for accessibility issues as before/after diffs.
"""

import json
from dataclasses import dataclass

from .models import generate, extract_json
from .scanner import Issue


REMEDIATE_SYSTEM = (
    "You are an accessibility remediation expert. Given accessibility issues, "
    "generate specific HTML/ARIA code fixes.\n\n"
    "Rules:\n"
    "- Generate minimal, targeted fixes\n"
    "- Use semantic HTML over ARIA when possible\n"
    "- Prefer native elements (button > div[role=button])\n"
    "- Include before/after code snippets\n"
    "- Each fix must be independently applicable\n\n"
    "Output valid JSON only."
)

REMEDIATE_PROMPT = """Fix these accessibility issues on {url}.

{issues_json}

Return JSON array. Each fix: rule_id, fix_type (html/aria/css), description, before, after, wcag, confidence (0-1), notes."""


@dataclass
class CodeFix:
    rule_id: str
    fix_type: str  # html, aria, css
    description: str
    before: str
    after: str
    wcag: str = ""
    confidence: float = 0.0
    notes: str = ""

    def to_dict(self) -> dict:
        return {
            "rule_id": self.rule_id,
            "fix_type": self.fix_type,
            "description": self.description,
            "before": self.before,
            "after": self.after,
            "wcag": self.wcag,
            "confidence": self.confidence,
            "notes": self.notes,
        }


def generate_fixes(
    issues: list[Issue],
    aria_tree: str = "",
    url: str = "",
    claude_api_key: str | None = None,
) -> list[CodeFix]:
    """Generate code fixes for accessibility issues."""
    if not issues:
        return []

    fixable = [i for i in issues if i.rule_id != "scan-error"]
    if not fixable:
        return []

    # Deduplicate by rule_id — same rule needs one fix, not 200
    seen_rules: dict[str, dict] = {}
    for i in fixable:
        if i.rule_id not in seen_rules:
            seen_rules[i.rule_id] = {
                "rule_id": i.rule_id,
                "wcag": i.wcag,
                "impact": i.impact,
                "description": i.description[:80],
                "element": i.selector or "",
            }

    deduped = list(seen_rules.values())[:10]
    issues_json = json.dumps(deduped, indent=1)

    prompt = REMEDIATE_PROMPT.format(
        url=url,
        issues_json=issues_json,
    )

    try:
        response = generate(
            prompt,
            task="remediation",
            system=REMEDIATE_SYSTEM,
            claude_api_key=claude_api_key,
        )
    except RuntimeError:
        return []

    if not response.text.strip():
        return []

    fixes = []
    try:
        parsed = json.loads(extract_json(response.text))
        if not isinstance(parsed, list):
            return []
        for item in parsed:
            fixes.append(
                CodeFix(
                    rule_id=item.get("rule_id", ""),
                    fix_type=item.get("fix_type", "html"),
                    description=item.get("description", ""),
                    before=item.get("before", ""),
                    after=item.get("after", ""),
                    wcag=item.get("wcag", ""),
                    confidence=item.get("confidence", 0.5),
                    notes=item.get("notes", ""),
                )
            )
    except (json.JSONDecodeError, KeyError, TypeError):
        pass

    return fixes


def fixes_to_markdown(fixes: list[CodeFix]) -> str:
    """Format fixes as readable markdown."""
    if not fixes:
        return "No fixes generated."

    lines = ["# TechAccess Suggested Fixes\n"]

    for i, fix in enumerate(fixes, 1):
        conf = fix.confidence
        indicator = "HIGH" if conf >= 0.7 else "MEDIUM" if conf >= 0.4 else "LOW"
        lines.append(f"## Fix {i}: `{fix.rule_id}` [{indicator} confidence]")
        lines.append(f"**{fix.description}**")
        if fix.wcag:
            lines.append(f"WCAG: {fix.wcag}")
        lines.append("")

        if fix.before:
            lines.append("**Before:**")
            lines.append(f"```html\n{fix.before}\n```")

        if fix.after:
            lines.append("**After:**")
            lines.append(f"```html\n{fix.after}\n```")

        if fix.notes:
            lines.append(f"> Note: {fix.notes}")
        lines.append("")

    lines.append(f"---\n*{len(fixes)} fixes generated by TechAccess AI*")
    return "\n".join(lines)


def fixes_to_json(fixes: list[CodeFix]) -> str:
    """Format fixes as JSON."""
    return json.dumps([f.to_dict() for f in fixes], indent=2)
