"""TechAccess Report Generators.

Formats scan results into JSON, Markdown, and SARIF output.
"""

import json
from datetime import datetime

from .scanner import ScanResult
from .score import Score


def to_json(result: ScanResult, score: Score) -> str:
    """Generate JSON report."""
    report = {
        "tool": "techaccess",
        "version": "0.1.0",
        "timestamp": result.timestamp,
        "url": result.url,
        "scan_time_ms": result.scan_time_ms,
        "viewports": result.viewports_tested,
        "score": score.to_dict(),
        "issues": result.to_dict()["issues"],
        "axe_summary": result.axe_summary,
    }
    return json.dumps(report, indent=2)


def to_markdown(result: ScanResult, score: Score) -> str:
    """Generate Markdown report (good for PRs and terminal output)."""
    lines = []

    # Header
    grade_emoji = {
        "A+": "🟢", "A": "🟢", "A-": "🟢",
        "B+": "🟡", "B": "🟡", "B-": "🟡",
        "C+": "🟠", "C": "🟠", "C-": "🟠",
        "D+": "🔴", "D": "🔴", "D-": "🔴",
        "F": "💀",
    }
    emoji = grade_emoji.get(score.grade, "")

    lines.append(f"# {emoji} TechAccess Accessibility Report")
    lines.append("")
    lines.append(f"**URL:** {result.url}")
    lines.append(f"**Score:** {score.value}/100 ({score.grade})")
    lines.append(f"**Scan time:** {result.scan_time_ms}ms")
    lines.append(f"**Viewports:** {', '.join(result.viewports_tested)}")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Impact | Count |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Critical | {score.critical} |")
    lines.append(f"| Serious | {score.serious} |")
    lines.append(f"| Moderate | {score.moderate} |")
    lines.append(f"| Minor | {score.minor} |")
    lines.append(f"| **Total** | **{score.total_issues}** |")
    lines.append("")

    if not result.issues:
        lines.append("No accessibility issues found. Great work!")
        return "\n".join(lines)

    # Issues by impact
    for impact in ["critical", "serious", "moderate", "minor"]:
        impact_issues = [i for i in result.issues if i.impact == impact]
        if not impact_issues:
            continue

        lines.append(f"## {impact.title()} Issues ({len(impact_issues)})")
        lines.append("")

        # Deduplicate by rule_id for cleaner output
        seen: dict[str, list] = {}
        for issue in impact_issues:
            seen.setdefault(issue.rule_id, []).append(issue)

        for rule_id, instances in seen.items():
            first = instances[0]
            wcag_label = f" (WCAG {first.wcag})" if first.wcag else ""
            lines.append(f"### `{rule_id}`{wcag_label}")
            lines.append(f"{first.description}")
            if first.help_url:
                lines.append(f"[Learn more]({first.help_url})")
            lines.append("")

            for inst in instances[:3]:  # Show up to 3 examples
                element = inst.element_html[:120] if inst.element_html else "N/A"
                lines.append(f"- **{inst.viewport}**: `{element}`")

            if len(instances) > 3:
                lines.append(f"- ... and {len(instances) - 3} more")
            lines.append("")

    # axe-core summary
    if result.axe_summary:
        lines.append("## axe-core Summary")
        lines.append("")
        for key, val in result.axe_summary.items():
            lines.append(f"- **{key}:** {val}")
        lines.append("")

    lines.append("---")
    lines.append(f"*Generated by [TechAccess](https://github.com/sophiacave/techaccess) v0.1.0*")

    return "\n".join(lines)


def to_sarif(result: ScanResult) -> str:
    """Generate SARIF report for GitHub Code Scanning integration."""
    sarif = {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "TechAccess",
                    "version": "0.1.0",
                    "informationUri": "https://github.com/sophiacave/techaccess",
                    "rules": [],
                }
            },
            "results": [],
        }],
    }

    run = sarif["runs"][0]
    seen_rules: set[str] = set()

    for issue in result.issues:
        if issue.rule_id not in seen_rules:
            seen_rules.add(issue.rule_id)
            run["tool"]["driver"]["rules"].append({
                "id": issue.rule_id,
                "shortDescription": {"text": issue.description},
                "helpUri": issue.help_url or "",
                "properties": {"wcag": issue.wcag} if issue.wcag else {},
            })

        level_map = {"critical": "error", "serious": "error", "moderate": "warning", "minor": "note"}
        run["results"].append({
            "ruleId": issue.rule_id,
            "level": level_map.get(issue.impact, "warning"),
            "message": {"text": f"{issue.description} ({issue.viewport})"},
            "locations": [{
                "physicalLocation": {
                    "artifactLocation": {"uri": result.url},
                    "region": {"snippet": {"text": issue.element_html[:200] if issue.element_html else ""}},
                }
            }],
        })

    return json.dumps(sarif, indent=2)
